name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.10  # Use a stable and widely supported version
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - scikit-learn
  - jinja2
  - tqdm
  - requests
  - pyproj
  - folium
  - shapely
  - fiona
  - rasterio
  - pyogrio
  - h5py
  - joblib

  # Compression libraries
  - zlib
  - lz4-c
  - snappy
  - libtiff

  # Image and plotting
  - pillow
  - fonttools

  # Optional for better performance or specific tasks
  - openblas
  - gdal
  - pycparser

  # For datetime operations
  - python-dateutil
  - pytz

  # Ensure pip is available
  - pip

  # Optional: Add any specific pip packages you need
  - pip:
    - xyzservices
    - branca
